=== Henry-Peng/Java_001/202005/20200520/hospitals.dtd
<?xml version="1.0" encoding="UTF-8"?>
	<!--hospitals  -->
	<!ELEMENT hospitals (hospital+)>
	<!ATTLIST hospital name CDATA #REQUIRED>
	<!ELEMENT hospital (department+)>
	<!ATTLIST department name CDATA #REQUIRED>
	<!ELEMENT department (area,level,doctors,patients)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT area (#PCDATA)>
	<!ELEMENT level (#PCDATA)>
	<!ELEMENT doctors (directors,doctor,nurses)>
	<!ELEMENT directors (#PCDATA)>
	<!ELEMENT doctor (#PCDATA)>
	<!ELEMENT nurses (#PCDATA)>
	<!ELEMENT patients (ongoing,await)>
	<!ELEMENT ongoing (#PCDATA)>
	<!ELEMENT await (#PCDATA)>

=== Henry-Peng/Java_001/202005/20200520/hospitals.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE hospitals SYSTEM "hospitals.dtd">

<hospitals>
	<hospital name="九龙医院">
		<department name="内科">
			<area>二楼东</area>
			<level>三级</level>
			<doctors>
				<directors>2</directors>
				<doctor>6</doctor>
				<nurses>4</nurses>
			</doctors>
			<patients>
				<ongoing>3</ongoing>
				<await>12</await>
			</patients>
		</department>
		<department name="外科">
			<area>二楼西</area>
			<level>三级</level>
			<doctors>
				<directors>2</directors>
				<doctor>5</doctor>
				<nurses>6</nurses>
			</doctors>
			<patients>
				<ongoing>3</ongoing>
				<await>1</await>
			</patients>
		</department>
		<department name="营养科">
			<area>三楼东</area>
			<level>二级</level>
			<doctors>
				<directors>3</directors>
				<doctor>6</doctor>
				<nurses>5</nurses>
			</doctors>
			<patients>
				<ongoing>4</ongoing>
				<await>0</await>
			</patients>
		</department>
		<department name="儿科">
			<area>三楼西</area>
			<level>二级</level>
			<doctors>
				<directors>3</directors>
				<doctor>6</doctor>
				<nurses>3</nurses>
			</doctors>
			<patients>
				<ongoing>6</ongoing>
				<await>13</await>
			</patients>
		</department>
		<department name="骨科">
			<area>四楼西</area>
			<level>三级</level>
			<doctors>
				<directors>3</directors>
				<doctor>7</doctor>
				<nurses>9</nurses>
			</doctors>
			<patients>
				<ongoing>5</ongoing>
				<await>9</await>
			</patients>
		</department>
	</hospital>
	<hospital name="三甲医院">
		<department name="内科">
			<area>二楼东</area>
			<level>三级</level>
			<doctors>
				<directors>2</directors>
				<doctor>6</doctor>
				<nurses>4</nurses>
			</doctors>
			<patients>
				<ongoing>3</ongoing>
				<await>12</await>
			</patients>
		</department>
		<department name="外科">
			<area>二楼西</area>
			<level>三级</level>
			<doctors>
				<directors>2</directors>
				<doctor>5</doctor>
				<nurses>6</nurses>
			</doctors>
			<patients>
				<ongoing>3</ongoing>
				<await>1</await>
			</patients>
		</department>
		<department name="营养科">
			<area>三楼东</area>
			<level>二级</level>
			<doctors>
				<directors>3</directors>
				<doctor>6</doctor>
				<nurses>5</nurses>
			</doctors>
			<patients>
				<ongoing>4</ongoing>
				<await>0</await>
			</patients>
		</department>
		<department name="儿科">
			<area>三楼西</area>
			<level>二级</level>
			<doctors>
				<directors>3</directors>
				<doctor>6</doctor>
				<nurses>3</nurses>
			</doctors>
			<patients>
				<ongoing>6</ongoing>
				<await>13</await>
			</patients>
		</department>
	</hospital>
	<hospital name="协和医院">
		<department name="内科">
			<area>二楼东</area>
			<level>三级</level>
			<doctors>
				<directors>2</directors>
				<doctor>6</doctor>
				<nurses>4</nurses>
			</doctors>
			<patients>
				<ongoing>3</ongoing>
				<await>12</await>
			</patients>
		</department>
		<department name="外科">
			<area>二楼西</area>
			<level>三级</level>
			<doctors>
				<directors>2</directors>
				<doctor>5</doctor>
				<nurses>6</nurses>
			</doctors>
			<patients>
				<ongoing>3</ongoing>
				<await>1</await>
			</patients>
		</department>
		<department name="营养科">
			<area>三楼东</area>
			<level>二级</level>
			<doctors>
				<directors>3</directors>
				<doctor>6</doctor>
				<nurses>5</nurses>
			</doctors>
			<patients>
				<ongoing>4</ongoing>
				<await>0</await>
			</patients>
		</department>
		<department name="儿科">
			<area>三楼西</area>
			<level>二级</level>
			<doctors>
				<directors>3</directors>
				<doctor>6</doctor>
				<nurses>3</nurses>
			</doctors>
			<patients>
				<ongoing>6</ongoing>
				<await>13</await>
			</patients>
		</department>
	</hospital>
</hospitals>
